### ISSUE TITLE
Ndef reading

### ISSUE THREAD

**Issue by eek** [gossel-j/node-mifare-pcsc#2]
Any ideas on how to read a NDEF Messages easy with your package? pcsc-lite is the only one that reads the device...

**Comment by jbgosselin** [comment]
My package was made to read directly the data inside but I'm sure there is a way to read NDEF message. I'm sure we can find some interesting things about NDEF [there](http://www.eet-china.com/ARTICLES/2006AUG/PDF/NFCForum-TS-NDEF.pdf).
I can't really help a lot because I don't have reader anymore. but Pull-request are welcome

**Comment by eek** [comment]
I changed the callback to return the raw data and I manage to read the NDEF message from my tag reading blocks from 3-8

```
var mifare = require("../lib");
var ndef = require('ndef');

mifare.onCard(function(card) {
  readNextBlock(card, 3, []);
});


function readNextBlock(card, block, finalData){
  card.readBlock(block,16, function(err, data){
    //console.log('block', block, 'finalData', finalData);
    finalData = finalData.concat(data.toJSON().data);
    if(block === 8){
      console.log(finalData);
      var message = ndef.decodeMessage(finalData);
      console.log('Message', message);
      console.log('Stringify', ndef.stringify(message));
    }else{
      readNextBlock(card, ++block, finalData);
    }
  });

}
```

Also used the `ndef` npm package to decode the Message. I will try playing with it more to see what are the exact blocks in which the TEXT is stored. 

Currently I'm experimenting :)

I'll do a pull request if what I did will be useful :D

Thanks for the base start! :)

**Comment by jbgosselin** [comment]
@eek Great ! If the ndef package works good then we can manage to add it to the lib afterward or even recode it to not be dependent about it. We will see !

I should be able to soon have an nfc reader to see if it works, maybe even the same as you.

**Comment by jbgosselin** [comment]
@eek if you do pull request please follow the git flow pattern ;)

**Comment by eek** [comment]
Block 6, length 16 worked to get the NDEF encoded message from the NTAG213. I had only 12 bytes of data, so I also got some weird ending characters :) from the ndef decoded message :)

**Comment by jbgosselin** [comment]
@eek I see, I think I'll make a new package that will handle mifare and ntag and maybe more kind of tags :) Maybe handle NDEF message too. I'll close this issue and you can follow me to see the new package :)
