### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by eek** [gossel-j/node-mifare-pcsc#3]
I also got an error for the default example:

```
New Reader(ACS ACR1252 CL Reader)
Reader(ACS ACR1252 CL Reader) card inserted
Error on getUID: undefined
/Volumes/Work/node-mifare-pcsc/index.js:67
        throw new Error("Undefined data: " + data.toString("hex"));
        ^

Error: Undefined data: 0460e9b2953c
    at /node-mifare-pcsc/index.js:67:9
```

This is my console output

**Comment by jbgosselin** [comment]
Hi eek, sorry but it's been such long time i haven't played with NFC, i just did this library for some school purpose. I know it's working with the reader i was using (don't remember the reader name _sob_).

**Comment by jbgosselin** [comment]
I think it was an ACR122U, not sure

**Comment by jbgosselin** [comment]
@eek maybe you're not using a mifare card.
I just bought the same reader as you and the stickers sold with it was NTAG203 and the protocol is different than mifare.
Can you show me what kind of tag you're using ?

**Comment by jbgosselin** [comment]
maybe i could write kind of the same library that can read ntag and mifare card

**Comment by eek** [comment]
Yup, NTAG213 was the tag I was using :)
