### ISSUE TITLE
Switching to Buffer.from(...)

### ISSUE THREAD

**Issue by gabrielschulhof** [gossel-j/node-mifare-pcsc#4]
`new Buffer(...)` is deprecated and unsafe. Is it possible to move to `Buffer.from(...)` in [these locations](https://github.com/gossel-j/node-mifare-pcsc/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22)?

**Comment by jbgosselin** [comment]
Hello @gabrielschulhof ! Sorry for my very slow reaction I didn't received any notification for that ><
I would be glad to do this, do you want do a PR for that ?

**Comment by jbgosselin** [comment]
Sorry @gabrielschulhof , i just redo the whole project, i have to close this Issue
