### ISSUE TITLE
I have error with Error: Cannot find module '../lib'

### ISSUE THREAD

**Issue by sarakornmick** [gossel-j/node-mifare-pcsc#7]
Hi !!

I would like to someone help me. 
I have error Error: Cannot find module '../lib' when I run node nfc-uid-logger.js  

![image](https://user-images.githubusercontent.com/59719432/122864163-4f85a300-d34e-11eb-83ff-12801ea5e726.png)

So how I can fix. Please let me know. Thank you so much.

**Comment by jbgosselin** [comment]
Hi ! Can I have more info on your operation system and nodeJS version ? Thanks !

**Comment by sarakornmick** [comment]
I have nodejs version 10.18.1 
How I can do it ? 
Thanks !

**Comment by jbgosselin** [comment]
I think this is because you have to compile the library in typescript. I didn't finish the entire migration to typescript.
You could use the last version before moving to typescript. 
It is the tag `0.0.3`

**Comment by sarakornmick** [comment]
So, how I get last version? It's Last version of nodejs?

**Comment by jbgosselin** [comment]
No It's the version of my code.
If you pulled the code with git you can do :
`git fetch && git checkout 0.0.3` I think

**Comment by sarakornmick** [comment]
Ok. I will try again.
If I have a problem I will ask again. 
Thank you so much.
